# Development profile
# Activated when SPRING_PROFILES_ACTIVE=dev
spring.jpa.show-sql=true

# Database (MySQL) Fallback for local development
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/krushikranti_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:19301930}

# Security Fallbacks for local dev
app.jwt.secret=${JWT_SECRET:KrushiKranti_MySQL_Dev_Secret_Change_This_in_Prod}

# Component API Defaults for local dev
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:ddqomy456}
cloudinary.api-key=${CLOUDINARY_API_KEY:316197758646591}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:HDmxbVD5f2vZ4okS89PZjCdxA40}

razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_SSOb8U0IBeHUr4}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:cJ3L1qFuBTn2auWKQ45xIaTr}

spring.mail.username=${MAIL_USERNAME:krishnachavan35199@gmail.com}
spring.mail.password=${MAIL_PASSWORD:lrtstntjfbyxpotv}
